name: Deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: write
        steps:
            - uses: actions/checkout@v4

            - name: add nojekyll
              run: touch .nojekyll

            # deploy files to gh-pages
            - name: Deploy to gh-pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  personal_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: .
                  publish_branch: gh-pages
